version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u your_user --password=your_password"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb-data:
