version: '3.8'
services:

  yugabytedb:
    image: "yugabytedb/yugabyte:2024.2.0.0-b145"
    command: yugabyted start --enable_pg_parity_early_access --tserver_flags="ysql_pg_conf_csv={shared_preload_libraries='pg_stat_monitor'}" --initial_scripts_dir=/docker-entrypoint-initial_scripts_dir --background=false 
    environment:
      YSQL_PASSWORD: password
      YSQL_USER: yugabyte
    volumes:
       - ../data/init/postgresql:/docker-entrypoint-initial_scripts_dir
    ports: 
      - "5433:5433"
      - "15433:15433"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$YSQL_PASSWORD yugabyted connect ysql <<<''"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
